const User = require('../models/User');
const Exercise = require('../models/Exercise');
const Program = require('../models/Program');

const shuffle = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
};

const generateWorkoutPlan = async (req, res) => {
    const { daysPerWeek, goal, intensity } = req.body;

    try {
        const user = await User.findById(req.user._id);
        const allExercises = await Exercise.find({});

        const safeExercises = allExercises.filter(ex => {

            const isUnsafe = user.injuries.some(injury =>
                ex.muscleGroup.toLowerCase().includes(injury.toLowerCase()) ||
                (injury.toLowerCase().includes('knee') && ex.muscleGroup === 'Legs') ||
                (injury.toLowerCase().includes('back') && ex.muscleGroup === 'Back')
            );
            return !isUnsafe;
        });

        let split = [];
        if (daysPerWeek <= 3) {
            split = ['Full Body', 'Full Body', 'Full Body'];
        } else if (daysPerWeek == 4) {
            split = ['Upper Body', 'Lower Body', 'Upper Body', 'Lower Body'];
        } else {
            split = ['Push', 'Pull', 'Legs', 'Push', 'Pull', 'Legs'];
        }

        split = split.slice(0, daysPerWeek);

        const weeks = [];

        const weekDays = split.map((focus, index) => {
            let dayExercises = [];

            if (focus === 'Full Body') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Chest')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Back')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Legs')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Shoulders')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Arms')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Abs')).slice(0, 1),
                ];
            } else if (focus === 'Upper Body') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Chest')).slice(0, 2),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Back')).slice(0, 2),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Shoulders')).slice(0, 1),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Arms')).slice(0, 1),
                ];
            } else if (focus === 'Lower Body') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Legs')).slice(0, 4),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Abs')).slice(0, 2),
                ];
            } else if (focus === 'Push') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Chest')).slice(0, 2),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Shoulders')).slice(0, 2),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Arms')).slice(0, 1),
                ];
            } else if (focus === 'Pull') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Back')).slice(0, 3),
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Arms')).slice(0, 2),
                ];
            } else if (focus === 'Legs') {
                dayExercises = [
                    ...shuffle(safeExercises.filter(e => e.muscleGroup === 'Legs')).slice(0, 5),
                ];
            }

            return {
                day: `Day ${index + 1} - ${focus}`,
                isRestDay: false,
                exercises: dayExercises.map(ex => ({
                    name: ex.name,
                    sets: goal === 'Strength' ? 5 : goal === 'Muscle Gain' ? 3 : 4,
                    reps: goal === 'Strength' ? 5 : goal === 'Muscle Gain' ? 10 : 15,
                    weight: 0
                }))
            };
        });

        for (let i = 1; i <= 4; i++) {
            weeks.push({
                weekNumber: i,
                days: weekDays
            });
        }

        res.json({
            name: `AI - ${daysPerWeek} Day ${goal} Plan`,
            description: `A personalized ${intensity} intensity plan focusing on ${goal}. Generated by AI Coach.`,
            weeks: weeks,
            generatedAt: new Date()
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'AI Generation Failed' });
    }
};

const saveGeneratedPlan = async (req, res) => {
    try {
        const programData = req.body;

        const program = await Program.create({
            client: req.user._id,
            name: programData.name,
            description: programData.description,
            weeks: programData.weeks,
            trainer: null
        });

        res.status(201).json(program);

    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

module.exports = { generateWorkoutPlan, saveGeneratedPlan };
